Update control
disabled start

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -285,25 +285,25 @@ function start() {
   fi
 
   # Check for running app
-  if isrunning; then
-      echo "Application is already running"
-  else
-    ${WILDFLY_BIN_DIR}/standalone.sh -b $OPENSHIFT_WILDFLY_IP -bmanagement=$OPENSHIFT_WILDFLY_IP > $OPENSHIFT_WILDFLY_DIR/logs/server.log 2>&1 &
-    PROCESS_ID=$!
-    echo "$PROCESS_ID" > ${WILDFLY_PID_FILE}
+#  if isrunning; then
+#      echo "Application is already running"
+#  else
+#    ${WILDFLY_BIN_DIR}/standalone.sh -b $OPENSHIFT_WILDFLY_IP -bmanagement=$OPENSHIFT_WILDFLY_IP > $OPENSHIFT_WILDFLY_DIR/logs/server.log 2>&1 &
+#    PROCESS_ID=$!
+#    echo "$PROCESS_ID" > ${WILDFLY_PID_FILE}
 
-    rc=0
-    ishttpup || rc=$?
-    if [ $rc -eq 1 ]; then
-      echo "Timed out waiting for http listening port for $cartridge_type process"
-      exit 1
-    elif [ $rc -eq 2 ]; then
-      echo "$cartridge_type process failed to start"
-      exit 2
-    fi
+#    rc=0
+#    ishttpup || rc=$?
+#    if [ $rc -eq 1 ]; then
+#      echo "Timed out waiting for http listening port for $cartridge_type process"
+#      exit 1
+#    elif [ $rc -eq 2 ]; then
+#      echo "$cartridge_type process failed to start"
+#      exit 2
+#    fi
 
-    waitondeployments
-  fi
+#    waitondeployments
+#  fi
 }
 
 
